---
- name: Install prerequisite packages
  apt: name="apt-transport-https" state="present"
  when: elastic_use_repository

- name: Debian - Add Elasticsearch repository key
  apt_key: url="{{ elastic_gpgkey_url }}" state=present
  when: elastic_use_repository and elastic_gpgkey_url

- name: Debian - Add elasticsearch repository
  apt_repository:
    repo: "{{ elastic_apt_url }}"
    state: "present"
    filename: "elastic-{{ elastic_major_version }}"
  when: elastic_use_repository and elastic_apt_url
